name: exptools2
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=hf036a51_0
  - backports.zstd=1.3.0=py310hedc14a4_0
  - blosc=1.21.6=hd145fbb_1
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py310hab27952_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - c-blosc2=2.15.2=h62acda9_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h950ec3b_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h062c7ae_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hf166250_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h610c526_0
  - cython=3.2.4=py310h4a90db6_0
  - dav1d=1.2.1=h0dc2134_0
  - dbus=1.16.2=h6e7f9a9_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - ffmpeg=8.0.1=gpl_h22b1ac2_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hd951482_0
  - freetype=2.14.1=h694c41f_0
  - fribidi=1.0.16=h8616949_0
  - gdk-pixbuf=2.44.4=h07555a4_0
  - giflib=5.2.2=h10d778d_0
  - glib=2.86.3=h182e902_0
  - glib-tools=2.86.3=h8650975_0
  - glslang=16.1.0=h4770549_0
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.14=h21dd04a_2
  - greenlet=3.3.0=py310ha75780e_0
  - gst-plugins-base=1.24.11=h09840cc_0
  - gstreamer=1.24.11=h7d1b200_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=hc5d3ef4_0
  - hdf5=1.14.4=nompi_h1607680_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h355fb9f_2
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250512.1=cxx17_hfc00f1c_0
  - libaec=1.1.4=ha6bc127_0
  - libass=0.17.4=h87c4fc2_0
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libclang-cpp18.1=18.1.8=default_hc369343_16
  - libclang13=21.1.8=default_h5e75a71_0
  - libcurl=8.17.0=h7dd4100_1
  - libcxx=21.1.8=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libflac=1.5.0=hbafe72d_1
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libglib=2.86.3=hf241ffe_0
  - libhwloc=2.12.1=default_h273dbb7_1003
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libintl-devel=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - libllvm18=18.1.8=default_hc369343_11
  - libllvm21=21.1.8=h56e7563_0
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libntlm=1.8=h6e16a3a_0
  - libogg=1.3.5=he3325bb_1
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopenvino=2025.4.1=hcab4a1a_0
  - libopenvino-auto-batch-plugin=2025.4.1=h2d421a1_0
  - libopenvino-auto-plugin=2025.4.1=h2d421a1_0
  - libopenvino-hetero-plugin=2025.4.1=h662c39e_0
  - libopenvino-intel-cpu-plugin=2025.4.1=hcab4a1a_0
  - libopenvino-ir-frontend=2025.4.1=h662c39e_0
  - libopenvino-onnx-frontend=2025.4.1=hf46b987_0
  - libopenvino-paddle-frontend=2025.4.1=hf46b987_0
  - libopenvino-pytorch-frontend=2025.4.1=h6f32989_0
  - libopenvino-tensorflow-frontend=2025.4.1=h29144dc_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=h6f32989_0
  - libopus=1.6=h34defe6_0
  - libpng=1.6.53=h380d223_0
  - libpq=18.1=h1e038c5_2
  - libprotobuf=6.31.1=hcc66ac3_4
  - librsvg=2.60.0=h2da6fc3_0
  - libsndfile=1.2.2=h4b11300_2
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.1=hb99441e_1
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.1=ha0a348c_1
  - libusb=1.0.29=h2287256_0
  - libuv=1.51.0=h58003a5_1
  - libvorbis=1.3.7=ha059160_2
  - libvpx=1.15.2=heffb93a_0
  - libvulkan-loader=1.4.328.1=hfc0b2d5_0
  - libwebp=1.6.0=h5442d53_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h7b7ecba_0
  - libxml2-16=2.15.1=ha1d9b0f_0
  - libxslt=1.1.43=h486b42e_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - lxml=6.0.2=py310ha2fbfbd_2
  - lz4-c=1.10.0=h240833e_1
  - matplotlib=3.10.8=py310h2ec42d9_0
  - matplotlib-base=3.10.8=py310h2102b89_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpg123=1.32.9=h78e78a4_0
  - msgpack-python=1.1.2=py310h8cf47bc_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nspr=4.38=hee0b3f1_0
  - nss=3.118=h2b2a826_0
  - numexpr=2.14.1=py310h4795a84_1
  - numpy=2.2.6=py310h07c5b4d_0
  - openh264=2.6.0=h4883158_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openldap=2.6.10=hd8a590d_0
  - openpyxl=3.1.5=py310h20ca25a_2
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h39ce848_1
  - pango=1.56.4=h6ef8af8_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=h13923f0_0
  - pillow=12.0.0=py310h3efcd4b_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=ha059160_1
  - ply=3.11=pyhd8ed1ab_3
  - proglog=0.1.10=pyhaa61c55_0
  - psutil=7.2.1=py310h8bcfd8d_0
  - pthread-stubs=0.4=h00291cd_1002
  - pugixml=1.15=h46091d4_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pyopengl=3.1.10=pyh534df25_2
  - pyosf=1.0.5=pyhd8ed1ab_3
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyqt=5.15.11=py310h6c6f83e_2
  - pyqt5-sip=12.17.0=py310h40a7462_2
  - pyserial=3.5=pyhcf101f3_2
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - pytables=3.10.1=py310hb5a30d5_4
  - python=3.10.19=h988dfef_2_cpython
  - python-bidi=0.6.7=py310hf24d99c_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python.app=1.4=py310h1b7cace_5
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310hd951482_0
  - pyzmq=27.1.0=py310hbbd5e6a_0
  - qhull=2020.2=h3c5361c_5
  - qt=5.15.15=hec7e8b5_0
  - qt-main=5.15.15=hf9f191d_6
  - qt-webengine=5.15.15=h46887bd_1
  - readline=8.3=h68b038d_0
  - requests=2.32.5=pyhcf101f3_1
  - sdl2=2.32.56=h53ec75d_0
  - sdl3=3.2.30=h59d2431_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - shaderc=2025.5=hda4194c_0
  - sip=6.10.0=py310ha75780e_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - spirv-tools=2025.4=hcb651aa_0
  - statsmodels=0.14.6=py310h0bce67a_0
  - svt-av1=3.1.2=h21dd04a_0
  - tbb=2022.3.0=hf0c99ee_1
  - tk=8.6.13=hf689a15_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py310h2513d93_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py310hd2d5e8d_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wxpython=4.2.4=py310hdfac0a5_0
  - wxwidgets=3.2.8.1=h07365d8_2
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zlib-ng=2.2.5=h55e386d_1
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - beautifulsoup4==4.14.3
      - cryptography==46.0.3
      - elementpath==5.1.0
      - esprima==4.0.1
      - exptools2==0.1.dev0
      - ffpyplayer==4.5.3
      - freetype-py==2.5.1
      - future==1.0.0
      - gevent==25.5.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - ifaddr==0.2.0
      - jedi==0.19.2
      - json-tricks==3.17.3
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - meshpy==2025.1.1
      - msgpack-numpy==0.4.8
      - opencv-python==4.12.0.88
      - parso==0.8.5
      - psychopy==2025.2.3
      - psychopy-ext==0.6.0.4
      - psychtoolbox==3.0.19.14
      - pyarrow==22.0.0
      - pygame==2.6.1
      - pyglet==1.5.27
      - pyobjc==12.1
      - pyobjc-core==12.1
      - pyobjc-framework-accessibility==12.1
      - pyobjc-framework-accounts==12.1
      - pyobjc-framework-addressbook==12.1
      - pyobjc-framework-adservices==12.1
      - pyobjc-framework-adsupport==12.1
      - pyobjc-framework-applescriptkit==12.1
      - pyobjc-framework-applescriptobjc==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-apptrackingtransparency==12.1
      - pyobjc-framework-arkit==12.1
      - pyobjc-framework-audiovideobridging==12.1
      - pyobjc-framework-authenticationservices==12.1
      - pyobjc-framework-automaticassessmentconfiguration==12.1
      - pyobjc-framework-automator==12.1
      - pyobjc-framework-avfoundation==12.1
      - pyobjc-framework-avkit==12.1
      - pyobjc-framework-avrouting==12.1
      - pyobjc-framework-backgroundassets==12.1
      - pyobjc-framework-browserenginekit==12.1
      - pyobjc-framework-businesschat==12.1
      - pyobjc-framework-calendarstore==12.1
      - pyobjc-framework-callkit==12.1
      - pyobjc-framework-carbon==12.1
      - pyobjc-framework-cfnetwork==12.1
      - pyobjc-framework-cinematic==12.1
      - pyobjc-framework-classkit==12.1
      - pyobjc-framework-cloudkit==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-collaboration==12.1
      - pyobjc-framework-colorsync==12.1
      - pyobjc-framework-compositorservices==12.1
      - pyobjc-framework-contacts==12.1
      - pyobjc-framework-contactsui==12.1
      - pyobjc-framework-coreaudio==12.1
      - pyobjc-framework-coreaudiokit==12.1
      - pyobjc-framework-corebluetooth==12.1
      - pyobjc-framework-coredata==12.1
      - pyobjc-framework-corehaptics==12.1
      - pyobjc-framework-corelocation==12.1
      - pyobjc-framework-coremedia==12.1
      - pyobjc-framework-coremediaio==12.1
      - pyobjc-framework-coremidi==12.1
      - pyobjc-framework-coreml==12.1
      - pyobjc-framework-coremotion==12.1
      - pyobjc-framework-coreservices==12.1
      - pyobjc-framework-corespotlight==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-corewlan==12.1
      - pyobjc-framework-cryptotokenkit==12.1
      - pyobjc-framework-datadetection==12.1
      - pyobjc-framework-devicecheck==12.1
      - pyobjc-framework-devicediscoveryextension==12.1
      - pyobjc-framework-dictionaryservices==12.1
      - pyobjc-framework-discrecording==12.1
      - pyobjc-framework-discrecordingui==12.1
      - pyobjc-framework-diskarbitration==12.1
      - pyobjc-framework-dvdplayback==12.1
      - pyobjc-framework-eventkit==12.1
      - pyobjc-framework-exceptionhandling==12.1
      - pyobjc-framework-executionpolicy==12.1
      - pyobjc-framework-extensionkit==12.1
      - pyobjc-framework-externalaccessory==12.1
      - pyobjc-framework-fileprovider==12.1
      - pyobjc-framework-fileproviderui==12.1
      - pyobjc-framework-findersync==12.1
      - pyobjc-framework-fsevents==12.1
      - pyobjc-framework-fskit==12.1
      - pyobjc-framework-gamecenter==12.1
      - pyobjc-framework-gamecontroller==12.1
      - pyobjc-framework-gamekit==12.1
      - pyobjc-framework-gameplaykit==12.1
      - pyobjc-framework-gamesave==12.1
      - pyobjc-framework-healthkit==12.1
      - pyobjc-framework-imagecapturecore==12.1
      - pyobjc-framework-inputmethodkit==12.1
      - pyobjc-framework-installerplugins==12.1
      - pyobjc-framework-instantmessage==12.1
      - pyobjc-framework-intents==12.1
      - pyobjc-framework-intentsui==12.1
      - pyobjc-framework-iobluetooth==12.1
      - pyobjc-framework-iobluetoothui==12.1
      - pyobjc-framework-iosurface==12.1
      - pyobjc-framework-ituneslibrary==12.1
      - pyobjc-framework-kernelmanagement==12.1
      - pyobjc-framework-latentsemanticmapping==12.1
      - pyobjc-framework-launchservices==12.1
      - pyobjc-framework-libdispatch==12.1
      - pyobjc-framework-libxpc==12.1
      - pyobjc-framework-linkpresentation==12.1
      - pyobjc-framework-localauthentication==12.1
      - pyobjc-framework-localauthenticationembeddedui==12.1
      - pyobjc-framework-mailkit==12.1
      - pyobjc-framework-mapkit==12.1
      - pyobjc-framework-mediaaccessibility==12.1
      - pyobjc-framework-mediaextension==12.1
      - pyobjc-framework-medialibrary==12.1
      - pyobjc-framework-mediaplayer==12.1
      - pyobjc-framework-mediatoolbox==12.1
      - pyobjc-framework-metal==12.1
      - pyobjc-framework-metalfx==12.1
      - pyobjc-framework-metalkit==12.1
      - pyobjc-framework-metalperformanceshaders==12.1
      - pyobjc-framework-metalperformanceshadersgraph==12.1
      - pyobjc-framework-metrickit==12.1
      - pyobjc-framework-mlcompute==12.1
      - pyobjc-framework-modelio==12.1
      - pyobjc-framework-multipeerconnectivity==12.1
      - pyobjc-framework-naturallanguage==12.1
      - pyobjc-framework-netfs==12.1
      - pyobjc-framework-network==12.1
      - pyobjc-framework-networkextension==12.1
      - pyobjc-framework-notificationcenter==12.1
      - pyobjc-framework-opendirectory==12.1
      - pyobjc-framework-osakit==12.1
      - pyobjc-framework-oslog==12.1
      - pyobjc-framework-passkit==12.1
      - pyobjc-framework-pencilkit==12.1
      - pyobjc-framework-phase==12.1
      - pyobjc-framework-photos==12.1
      - pyobjc-framework-photosui==12.1
      - pyobjc-framework-preferencepanes==12.1
      - pyobjc-framework-pushkit==12.1
      - pyobjc-framework-quartz==12.1
      - pyobjc-framework-quicklookthumbnailing==12.1
      - pyobjc-framework-replaykit==12.1
      - pyobjc-framework-safariservices==12.1
      - pyobjc-framework-safetykit==12.1
      - pyobjc-framework-scenekit==12.1
      - pyobjc-framework-screencapturekit==12.1
      - pyobjc-framework-screensaver==12.1
      - pyobjc-framework-screentime==12.1
      - pyobjc-framework-scriptingbridge==12.1
      - pyobjc-framework-searchkit==12.1
      - pyobjc-framework-security==12.1
      - pyobjc-framework-securityfoundation==12.1
      - pyobjc-framework-securityinterface==12.1
      - pyobjc-framework-securityui==12.1
      - pyobjc-framework-sensitivecontentanalysis==12.1
      - pyobjc-framework-servicemanagement==12.1
      - pyobjc-framework-sharedwithyou==12.1
      - pyobjc-framework-sharedwithyoucore==12.1
      - pyobjc-framework-shazamkit==12.1
      - pyobjc-framework-social==12.1
      - pyobjc-framework-soundanalysis==12.1
      - pyobjc-framework-speech==12.1
      - pyobjc-framework-spritekit==12.1
      - pyobjc-framework-storekit==12.1
      - pyobjc-framework-symbols==12.1
      - pyobjc-framework-syncservices==12.1
      - pyobjc-framework-systemconfiguration==12.1
      - pyobjc-framework-systemextensions==12.1
      - pyobjc-framework-threadnetwork==12.1
      - pyobjc-framework-uniformtypeidentifiers==12.1
      - pyobjc-framework-usernotifications==12.1
      - pyobjc-framework-usernotificationsui==12.1
      - pyobjc-framework-videosubscriberaccount==12.1
      - pyobjc-framework-videotoolbox==12.1
      - pyobjc-framework-virtualization==12.1
      - pyobjc-framework-vision==12.1
      - pyobjc-framework-webkit==12.1
      - pyparallel==0.2.2
      - pyqt6==6.10.1
      - pyqt6-qt6==6.10.1
      - pyqt6-sip==13.10.3
      - pysoundcard==0.5.2
      - python-gitlab==7.1.0
      - python-vlc==3.0.21203
      - questplus==2023.1
      - requests-toolbelt==1.0.0
      - scipy==1.14.1
      - setuptools==70.3.0
      - smmap==5.0.2
      - sounddevice==0.5.3
      - soupsieve==2.8.1
      - ujson==5.11.0
      - websockets==15.0.1
      - xarray==2025.6.1
      - xmlschema==4.3.0
      - zeroconf==0.148.0
      - zmq==0.0.0
      - zope-event==5.0
      - zope-interface==7.2
prefix: /opt/miniconda3/envs/exptools2
